# Setting up Travis CI with Docker to allow building and testing on the latest
# version of Ubuntu which is currently 17.04.
sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull ubuntu:17.04


install:
  - docker run "apt-get update"
  - docker run "apt-get install -y git swig python-setuptools gettext /
                python-dev python-numpy libgtk-3-dev python-gi-dev /
                libpng-dev liblcms2-dev libjson-c-dev gir1.2-gtk-3.0 /
                python-gi-cairo"

before_script:
    - docker run "git clone https://github.com/mypaint/libmypaint"
    - docker run "cd libmypaint"
    - docker run "./autogen.sh"
    - docker run "./configure --prefix=/usr"
    - docker run "make"
    - docker run "sudo make install"
    - docker run "cd .."
    - docker run "sudo rm -fr libmypaint"

script:
    - docker run "python setup.py build"
    - docker run "python setup.py nosetests --tests lib"
    - docker run "python setup.py test"
    - docker run "sudo python setup.py managed_install"
    - docker run "sudo python setup.py managed_uninstall"
    - docker run "sudo python setup.py install --root=/app/ --prefix=."
    - docker run "bash -ex appimage/appimage.sh || true"
