name: Windows_Test

on:
    - push
    - pull_request

jobs:
    windows_test:
        name: Windows
        runs-on: windows-latest
        strategy:
            matrix:
                msys2_arch: [x86_64, i686]
                include:
                    - msys2_arch: x86_64
                      msystem: MINGW64
                    - msys2_arch: i686
                      msystem: MINGW32
        defaults:
            run:
                shell: msys2 {0}
        steps:
            - uses: actions/checkout@v4
            - uses: msys2/setup-msys2@v2
              with:
                  msystem: ${{ matrix.msystem }}
                  arch: ${{ matrix.msys2_arch }}
                  update: true
                  install: >-
                      base-devel
                      git
                      mingw-w64-${{ matrix.msys2_arch }}-toolchain
                      mingw-w64-${{ matrix.msys2_arch }}-pkg-config
                      mingw-w64-${{ matrix.msys2_arch }}-glib2
                      mingw-w64-${{ matrix.msys2_arch }}-gtk3
                      mingw-w64-${{ matrix.msys2_arch }}-json-c
                      mingw-w64-${{ matrix.msys2_arch }}-lcms2
                      mingw-w64-${{ matrix.msys2_arch }}-python3-cairo
                      mingw-w64-${{ matrix.msys2_arch }}-pygobject-devel
                      mingw-w64-${{ matrix.msys2_arch }}-python3-gobject
                      mingw-w64-${{ matrix.msys2_arch }}-python3-numpy
                      mingw-w64-${{ matrix.msys2_arch }}-hicolor-icon-theme
                      mingw-w64-${{ matrix.msys2_arch }}-librsvg
                      mingw-w64-${{ matrix.msys2_arch }}-gobject-introspection
                      mingw-w64-${{ matrix.msys2_arch }}-python3-pytest
                      mingw-w64-${{ matrix.msys2_arch }}-python3-setuptools
                      mingw-w64-${{ matrix.msys2_arch }}-swig
                      mingw-w64-${{ matrix.msys2_arch }}-gsettings-desktop-schemas
            - name: "Install libmypaint"
              run: |
                  git clone https://github.com/mypaint/libmypaint
                  pushd libmypaint
                  ./autogen.sh
                  ./configure --prefix=/usr
                  make
                  make install
                  popd
                  rm -fr libmypaint
            - name: "Install mypaint-brushes"
              run: |
                  git clone https://github.com/mypaint/mypaint-brushes
                  pushd mypaint-brushes
                  ./autogen.sh
                  ./configure --prefix=/usr
                  make
                  make install
                  popd
                  rm -fr mypaint-brushes
            - name: "Build mypaint"
              run: |
                  which python3
                  python3 --version
                  python3 setup.py build_ext
                  python3 setup.py build
            - name: "Run tests"
              run: |
                  pytest --doctest-modules lib
                  pytest -rP
                  python3 setup.py clean --all
